language: bash
dist: trusty
sudo: required

before_install:
  - sudo apt-get update -q
  - sudo apt-get upgrade -q -y
  - docker version

before_script:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
      export DOCKER_TAG="latest";
    else
      export DOCKER_TAG="${TRAVIS_BRANCH}";
    fi

script:
  - >
    docker build
    --tag ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG} .

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG}

notifications:
  email:
    on_success: never
    on_failure: change
