language: bash
dist: trusty
group: travis_latest
sudo: required

if: |
  branch = master AND \
  NOT commit_message =~ /readme.md/ AND \
  NOT commit_message =~ /docker-compose.yml/ OR \
  TRAVIS_EVENT_TYPE = cron

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    - BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}"
    - DOCKER_DESCRIPTION="file hosting and personal cloud"
    - DOCKER_MAINTAINER="stlouisn"
    - DOCKER_NAME="nextcloud"
    - DOCKER_URL="https://nextcloud.com/"
    - SCHEMA_VERSION="1.0"
    - VCS_REF="$(git rev-parse --short HEAD)"
    - VCS_URL="$(git remote get-url origin | head -c-5)"
  matrix:
    - DOCKER_TAG="latest"
      DOCKER_VERSION="$((docker pull library/nextcloud:apache && docker run -it --rm library/nextcloud:apache /bin/bash -c env) | grep NEXTCLOUD_VERSION | awk -F '=' {'print $2'})"

before_install:
  - docker version
  - sudo /sbin/sysctl -w net.ipv4.conf.all.forwarding=1

install:

before_script:
  - sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' Dockerfile

script:
  - >
    docker build
    --label org.label-schema.build-date="${BUILD_DATE}"
    --label org.label-schema.build-number="${BUILD_NUMBER}"
    --label org.label-schema.description="${DOCKER_DESCRIPTION}"
    --label org.label-schema.maintainer="${DOCKER_MAINTAINER}"
    --label org.label-schema.name="${DOCKER_NAME}"
    --label org.label-schema.url="${DOCKER_URL}"
    --label org.label-schema.version="${DOCKER_VERSION}"
    --label org.label-schema.schema-version="${SCHEMA_VERSION}"
    --label org.label-schema.vcs-ref="${VCS_REF}"
    --label org.label-schema.vcs-url="${VCS_URL}"
    --tag ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}
    --pull .

after_success:
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_USERNAME}/${DOCKER_NAME}:${DOCKER_TAG}

notifications:
  email:
    on_success: never
    on_failure: change
