version: '2.4'

services:

  nextcloud:
    image: stlouisn/nextcloud
    container_name: nextcloud
    hostname: nextcloud
    environment:
      - LC_ALL=C.UTF-8
      - TZ=UTC
    restart: always
    volumes:
      - /docker/nextcloud/html:/var/www/html:rw
      - /docker/nextcloud/config:/var/www/html/config:rw
      - /docker/nextcloud/userdata:/var/www/html/data:rw
    tmpfs:
      - /var/log/supervisord
    ports:
      - 8080:80
