version: '2.4'

services:

  nextcloud:
    image: stlouisn/nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    environment:
      - LC_ALL=C.UTF-8
      - TZ=UTC
    restart: always
    volumes:
      - /docker/nextcloud/html:/var/www/html
      - /docker/nextcloud/config:/var/www/html/config
      - /docker/nextcloud/userdata:/var/www/html/data
    tmpfs:
      - /var/log/supervisord
    mem_limit: 1000M
    memswap_limit: 2000M
    logging:
      driver: json-file
        options:
          max-size: "10M"
          max-file: "3"
    ports:
      - 8080:80
